version: '3'

services:
  docker-mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=xa
      - MYSQL_PASSWORD=password
    ports:
      - 3308:3306

  app:
    image: thedockermaster001/springbootimage3.0
    ports:
       - 8091:8091
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.10.17:3306/db?autoReconnect=true&useSSL=false
    depends_on:
       - docker-mysql
